import { Education } from "./Education";

export const EDUCATIONS_ENG : Education[] = [
    {
        id: 7,
        uni_name:'Polytech Lyon, Claude Bernard University Lyon 1, Villeurbanne',
        degree:'Master1 MIAGE (Computer Methods Applied to Business Management)',
        faculty:'Computer Science',
        duration:'2022-2023',
    },
    {
        id: 6,
        uni_name:'Claude Bernard University Lyon 1, Villeurbanne',
        degree:'Bachelor of Science',
        faculty:'Computer Science',
        duration:'2021-2022',
    },
    {   id: 5,
        uni_name:'Institute of Technology Lyon1, Villeurbanne',
        degree:'University Diploma of Technology in Computer Science',
        faculty:'Computer Science',
        duration:'2020-2021',
    },
    {   id: 4,
        uni_name:'French Language and Culture Institute, Lyon Catholic University, France',
        degree:'University Diploma of French Language and Culture Level C1',
        faculty:'French Language',
        duration:'2018-2019',
    },
    {   id: 3,
        uni_name:'University of Strathclyde, Glasgow, The UK',
        degree:'MBA (Dean Scholarship)',
        faculty:'Business School',
        duration:'2011-2012',
    },
    {   id: 2,
        uni_name:'Chulalongkorn University, Bangkok,Thailand',
        degree:'MSc. Petrochemical Technology',
        faculty:'Petroleum and Petrochemical College',
        duration:'1999-2001',
    },
    {   id: 1,
        uni_name:'Kasetsart University, Bangkok,Thailand',
        degree:'Bachelor of Engineering',
        faculty:'Chemical Engineering',
        duration:'1995-1999',
    },    
]

export const EDUCATIONS_FR : Education[] = [
    {
        id: 7,
        uni_name:'Polytech Lyon, Université Claude Bernard Lyon 1, Villeurbanne',
        degree:'Master1 MIAGE (Méthodes Informatiques Appliquées à la Gestion des Entreprises)',
        faculty:'Informatique',
        duration:'2022-2023',
    },
    {
        id: 6,
        uni_name:'Université Claude Bernard Lyon 1, Villeurbanne',
        degree:'Licence 3',
        faculty:'Informatique',
        duration:'2021-2022',
    },
    {   id: 5,
        uni_name:'Institut Universitaire de Technologie, Lyon1, Villeurbanne',
        degree:'Diplôme Universitaire de Technologie',
        faculty:'Informatique',
        duration:'2020-2021',
    },
    {   id: 4,
        uni_name:'Institut de Langue et de Culture Françaises, Université Catholique de Lyon, France',
        degree:'Diplôme Universitaire de Langue et Culture Françaises niveau C1',
        faculty:'Lanque française',
        duration:'2018-2019',
    },
    {   id: 3,
        uni_name:'Université de Strathclyde, Glasgow, Écosse',
        degree:'MBA (bourse au mérite du doyen)',
        faculty:'École de commerce',
        duration:'2011-2012',
    },
    {   id: 2,
        uni_name:'Chulalongkorn Université, Bangkok, Thaïlande',
        degree:'MSc. en technologie pétrochimique',
        faculty:"École de Pétrole et Pétrochimique",
        duration:'1999-2001',
    },
    {   id: 1,
        uni_name:'Kasetsart Université, Bangkok,Thaïlande',
        degree:"Licence d'ingénierie",
        faculty:'Génie chimique',
        duration:'1995-1999',
    },    
]